### ISSUE TITLE
Tip: use doctoc to generate automatically Table of Content

### ISSUE THREAD

**Issue by jmgarnier** [brunofacca/zen-rails-security-checklist#11]
The link https://github.com/brunofacca/zen-rails-security-checklist#sensitive-data-exposure is broken in your ToC

I recommend https://github.com/thlorenz/doctoc which does a good job to automate this tedious task. Especially when it's in git hook 😉 

Thanks for sharing to the 🌍 ! 😸

**Comment by brunofacca** [comment]
Fixed it in f9b6c4ce15240abda673f0c723b1b35dee5887ff using doctoc.

Thanks!

**Comment by AArONnn12357999** [comment]
Good job guys:)
